apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-grafana-datasource
  labels:
    grafana_datasource: "1"
data:
  loki-grafana-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: loki
      type: loki
      url: http://loki.loki-system:3100/
      access: proxy
      isDefault: false
      readOnly: false
      editable: true
