# cluster role to allow the editing virtualService, and DestinationRules


apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aggregate-to-edit
  labels: 
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups: 
      - networking.istio.io
    resources: 
      - VirtualService 
      - DestinationRule
    verbs: 
      - create
      - update 
      - patch 
      - delete 
      - deletecollection