apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  deschedulerpolicy.yaml: |
    apiVersion: "descheduler/v1alpha1"
    kind: "DeschedulerPolicy"
    strategies:
      "RemoveDuplicates":
        enabled: true
      "RemovePodsViolatingInterPodAntiAffinity":
        enabled: true
      "RemovePodsViolatingNodeTaints":
        enabled: true
      "LowNodeUtilization":
        enabled: true
        params:
          nodeResourceUtilizationThresholds:
            thresholds:
              "cpu" : 20
              "memory": 20
              "pods": 20
            targetThresholds:
              "cpu" : 50
              "memory": 50
              "pods": 50
      "RemovePodsHavingTooManyRestarts":
        enabled: true
        params:
          RemovePodsHavingTooManyRestarts:
            podRestartThreshold: 100
            includingInitContainers: true
      "PodLifeTime":
        enabled: false
        params:
          maxPodLifeTimeSeconds: 604800