---
# Configure the helm repository on the deployment host. This
# adds the metrics server helm repository and updates the list
# of available helm charts.

- name: Setup Helm Repository
  kubernetes.core.helm_repository:
    name: metrics-server
    repo_url: "{{ metrics_server_helm_chart_repo }}"


- name: Install/Upgrade metrics-server
  block:
    - name: Create metrics-server Values File
      tempfile:
        state: file
        suffix: metrics-values
      register: metrics_values
      changed_when: false

    - name: Template metrics-server Values File
      template:
        src: values.metrics.yml.j2
        dest: "{{ metrics_values.path }}"
      diff: no
      changed_when: false


    # Install Metric server using the helm chart and apply the values template.
    # If ansible is running in check mode, then this will run helm with the diff option.
    - name: Deploy Metrics Server with values loaded from template
      kubernetes.core.helm:
        name: metrics-server
        chart_ref: metrics-server/metrics-server
        chart_version: "{{ metrics_server_chart_version }}"
        release_namespace: kube-system
        context: "{{ kube_context }}"
        values: "{{ lookup('template', '{{ metrics_values.path }}') | from_yaml }}"
        wait: true
